### PR TITLE
PHP version check

### PR DESCRIPTION
**Pull request by noplanman**
Use PHP for version checks.

Another thing that would be great, is to check versions before downloading the whole zip file.
What could be done, is to just fetch the `version.php` file from the GitHub repo and compare with that.
To download the whole zip every time to just say "version is the same" doesn't make sense.

### CODE REVIEW

**Comment by noplanman** [comment]
Have rebased. Any idea why the test is failing?

**Comment by aalaesar** [comment]
Everything is skipped just after the check version so we need to know what ansible gets.
- add debug task for var nc_upgrade_check_versions 
- add verbosity to the ansible command in .travis.yml
- add verbosity to the php script ?

**Comment by noplanman** [comment]
Yes I noticed that.

Will dig deeper on a separate branch later this evening :+1:

And yes to adding verbose Ansible output to travis!

**Comment by aalaesar** [comment]
ansible galaxy install v1.2 of install_nextcloud by the way
 but this should not be a problem as last PR passed

**Comment by noplanman** [comment]
Right, the problem was that travis has PHP 5.6 by default and I was going for PHP 7.
Do you know how to switch to PHP 7 when not using `php` as the default language?

Also, check [this build](https://travis-ci.org/noplanman/ansible-nextcloud-upgrade/builds/193246895). Any idea why this code just stops there? The exit code is clearly 0, but it just stops, no skip warning or anything. It just doesn't execute the last block 😕

**Comment by aalaesar** [comment]
Ok, there is a lot of things happening here:
- In this case, Travis do not uses php, it loads a vm.
By default it's an oooold Ubuntu 12.04 for linux testing
I tried to get debian and more recent ubuntu but I only managed to get the 14.04 from Travis... I suppose it has just 12.04 and 14.04 available.
If I understand correctly, the System's php is used to run the the php script and therefore the default version of the OS.
Ubuntu 1404 has an old PHP version and can't even run nextcloud 11.
That's why the test is an upgrade from nextcloud 9 to 10...
- So the version problem reveals that the _php script must be able to be launched on all systems_ this role is intended to be run on (Ubuntu 14-16 and debian 8+) _with their respective php version_
I'm not sure forcing php 7 in the test is good practice as it might not be the case in production.
- Verbosity adds soooooooooo much scrolling :thinking: .... But render the debug task redundant with the verbosity. **I suggest keeping verbosity but removing the debug task.** The `always` block may be the cause of the last issue.
- Thinking about the php dependency puzzle, I think that using python, as it is required on each client to run ansible's scripts, would be less problematic. Maybe doing a custom Ansible module... :thinking:

**Comment by noplanman** [comment]
What just came to me: This is a PHP project after all, so why not change the travis language to PHP?! We can install ansible separately and this gives us the chance to test multiple PHP versions!

Agreed on not forcing PHP7, I've removed it in my test branch.

Haha, talk about lots of scrolling! 😄 When I saw the scrollbar I couldn't believe it!
But yes, let's leave verbose on and remove the debug task 👍 

Mh, will try without the `always` block, seems super weird though 😕 

Thanks!

**Comment by aalaesar** [comment]
> What just came to me: This is a PHP project after all, so why not change the travis language to PHP?! We can install ansible separately and this gives us the chance to test multiple PHP versions!

I'm quite confident that the nextcloud team do it already  :wink: 
Here the role is focused on the upgrade process on modern debian OS and how to code it on ansible
So this might be called an Ansible project ... upgrading a PHP project. :smile: 
Note on install_nextcloud I added testing for multiple Ansible versions but not on this repo ...yet.

**Comment by noplanman** [comment]
Of course, you are SO right, how silly of me... Getting a bit taken away here 😄 

Right, I'll focus on finding this bug now and keep the check script as PHP compatible as possible 👍

**Comment by noplanman** [comment]
Using a local vagrant setup, this change works perfectly, I'm so confused...
Will try with different versions of Ansible now, just to make sure that's not the issue here.

**Comment by aalaesar** [comment]
I noted differences in Ansible version: Installed version is the latest, 2.2.1.0 on this role
May be something breaks. I'll add it to travis.yml on install_nextcloud (should work).

**Comment by noplanman** [comment]
Yep, different versions is the issue here, strange differences though when looking at the 2 failed ones 😕 
https://travis-ci.org/noplanman/ansible-nextcloud-upgrade/builds/193354626

Weird thing is that this PHP script causes the fail, even though it has nothing to do with it...

**Comment by aalaesar** [comment]
The php script is not in default for 18.1 &18.2 failures
- For 18.1. the version check passed ok , but it failed after to find a task file and rolled back to the rescue tasks. I don't know why it did'nt find it.
- For 18.2, this is just bad luck: install_nextcloud failed the installation because of the admin password starting with a - (your fix is not yet released) but ansible did'nt return the failure. Therefore Travis ran the upgrade role, which eventually failed.

**Comment by aalaesar** [comment]
If it works locally,
I suggest you to squash the branch and merge your changes from php_version_check_fix to the PR and we will see what happen next.

**Comment by noplanman** [comment]
Seems that earlier versions of Ansible handle task includes differently.
When including a task within a task, newer versions search from root, whereas older ones search from the current folder.

I fixed this by including from one folder up `../tasks/taskfile.yml`.

Hah, I literally just pushed a squashed and cleaned up version right before coming to read this 😇👍

**Comment by aalaesar** [comment]
> I fixed this by including from one folder up ../tasks/taskfile.yml.

Travis do not seems to like relative folders. :angry: 
I suggest using ansible variable {{ role_path }} to give an absolute path
example in install_nextcloud: https://github.com/aalaesar/install_nextcloud/blob/master/tasks/setup_env.yml#L15

**Comment by noplanman** [comment]
Em, travis isn't the problem here, the tests all pass with `../`. Maybe Ansible has issues with it in earlier versions?

Also, look who I found by chance: https://travis-ci.org/noplanman/ansible-nextcloud-upgrade/jobs/193382508#L618
Is this due to a wrong version being pulled from Ansible Galaxy?
Maybe create a new release which has this fix incorporated?

**Comment by aalaesar** [comment]
> Em, travis isn't the problem here, the tests all pass with ../. Maybe Ansible has issues with it in earlier versions?

Sorry, I assumed the fixed was already in your commit while Travis was messing with sub folders.
 
> Is this due to a wrong version being pulled from Ansible Galaxy?

Yes Ansible Galaxy pulls the last release, 1.2 for now. I'll look for doing a 1.2.1 just with your fix without breaking everything in the git repo :smile:

**Comment by noplanman** [comment]
> ...without breaking everything in the git repo 😄 

Haha, and here I am trying to make things better 😂

**Comment by noplanman** [comment]
Hmm, seems like travis is down at the moment, it isn't building anything 👎

**Comment by aalaesar** [comment]
Last build passed  :+1:  and has been run with install_nextcloud 1.2.1 as a bonus :sunglasses:

**Pull request merged**
